# Generated by Django 4.2.16 on 2025-12-14 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_type', models.IntegerField(blank=True, choices=[(10, '10시간'), (20, '20시간'), (50, '50시간'), (100, '100시간')], null=True)),
                ('coupon_registered_at', models.DateField(blank=True, null=True)),
                ('coupon_expires_at', models.DateField(blank=True, null=True)),
                ('coupon_status', models.CharField(choices=[('활성', '활성'), ('만료', '만료')], default='활성', max_length=10)),
                ('piano_category', models.CharField(blank=True, choices=[('수입', '수입'), ('국산', '국산')], max_length=10, null=True)),
                ('customer_name', models.CharField(max_length=100, verbose_name='예약자명')),
                ('phone_number', models.CharField(max_length=20, unique=True, verbose_name='전화번호')),
                ('remaining_time', models.IntegerField(default=0, verbose_name='잔여시간(분)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '쿠폰 고객',
                'verbose_name_plural': '쿠폰 고객 목록',
                'db_table': 'coupon_customers',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PAYMENT_GUIDE', '입금 안내'), ('CONFIRMATION', '확정 안내'), ('COUPON_CANCEL_TIME', '쿠폰 취소(잔여시간 부족)'), ('COUPON_CANCEL_TYPE', '쿠폰 취소(유형 불일치)'), ('NORMAL_CANCEL_CONFLICT', '일반 취소(동시간대 선입금 우선)'), ('DAWN_CONFIRM', '새벽 예약 확인')], max_length=64, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'message_templates',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naver_booking_id', models.CharField(default='', max_length=100, unique=True, verbose_name='예약번호')),
                ('customer_name', models.CharField(max_length=100, verbose_name='예약자명')),
                ('phone_number', models.CharField(max_length=20, verbose_name='전화번호')),
                ('room_name', models.CharField(max_length=100, verbose_name='예약룸명')),
                ('reservation_date', models.DateField(verbose_name='예약일자')),
                ('start_time', models.TimeField(verbose_name='시작시간')),
                ('end_time', models.TimeField(verbose_name='종료시간')),
                ('price', models.IntegerField(verbose_name='요금')),
                ('is_coupon', models.BooleanField(default=False, verbose_name='쿠폰여부')),
                ('account_sms_status', models.CharField(choices=[('전송전', '전송전'), ('전송완료', '전송완료'), ('전송실패', '전송실패'), ('입금확인전', '입금확인전')], default='전송전', max_length=20, verbose_name='계좌문자')),
                ('complete_sms_status', models.CharField(choices=[('전송전', '전송전'), ('전송완료', '전송완료'), ('전송실패', '전송실패'), ('입금확인전', '입금확인전')], default='입금확인전', max_length=20, verbose_name='완료문자')),
                ('reservation_status', models.CharField(choices=[('신청', '신청'), ('확정', '확정'), ('취소', '취소')], default='신청', max_length=20, verbose_name='예약상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '예약',
                'verbose_name_plural': '예약 목록',
                'db_table': 'reservations',
                'ordering': ['-created_at', '-reservation_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='CouponHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='예약자명')),
                ('room_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='예약룸명')),
                ('transaction_date', models.DateField(verbose_name='거래일자')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='시작시간')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='종료시간')),
                ('remaining_time', models.IntegerField(verbose_name='잔여시간(분)')),
                ('used_or_charged_time', models.IntegerField(verbose_name='사용/충전시간(분)')),
                ('transaction_type', models.CharField(choices=[('충전', '충전'), ('사용', '사용')], max_length=10, verbose_name='거래유형')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='pianos.couponcustomer', verbose_name='고객')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_histories', to='pianos.reservation', verbose_name='예약')),
            ],
            options={
                'verbose_name': '쿠폰 사용 이력',
                'verbose_name_plural': '쿠폰 사용 이력 목록',
                'db_table': 'coupon_history',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='거래고유번호')),
                ('transaction_date', models.DateField(verbose_name='거래일자')),
                ('transaction_time', models.TimeField(verbose_name='거래시간')),
                ('transaction_type', models.CharField(choices=[('입금', '입금'), ('출금', '출금')], max_length=10, verbose_name='거래구분')),
                ('amount', models.IntegerField(verbose_name='거래금액')),
                ('balance', models.IntegerField(verbose_name='거래후잔액')),
                ('depositor_name', models.CharField(blank=True, max_length=100, verbose_name='입금자명')),
                ('memo', models.TextField(blank=True, verbose_name='거래메모')),
                ('match_status', models.CharField(choices=[('확정전', '확정전'), ('확정완료', '확정완료'), ('취소', '취소')], default='확정전', max_length=10, verbose_name='매칭상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('matched_reservations', models.ManyToManyField(blank=True, related_name='matched_transactions', to='pianos.reservation', verbose_name='매칭된예약들')),
            ],
            options={
                'verbose_name': '계좌 거래 내역',
                'verbose_name_plural': '계좌 거래 내역 목록',
                'db_table': 'account_transactions',
                'ordering': ['-transaction_date', '-transaction_time'],
                'indexes': [models.Index(fields=['-transaction_date', '-transaction_time'], name='account_tra_transac_a7396b_idx'), models.Index(fields=['match_status'], name='account_tra_match_s_1bfce6_idx'), models.Index(fields=['depositor_name'], name='account_tra_deposit_f5212f_idx')],
            },
        ),
    ]
