# Generated by Django 4.2.16 on 2025-12-08 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CouponCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="예약자명"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="전화번호"
                    ),
                ),
                (
                    "remaining_time",
                    models.IntegerField(default=0, verbose_name="잔여시간(분)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "쿠폰 고객",
                "verbose_name_plural": "쿠폰 고객 목록",
                "db_table": "coupon_customers",
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="예약자명"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="전화번호"),
                ),
                (
                    "room_name",
                    models.CharField(max_length=100, verbose_name="예약룸명"),
                ),
                ("reservation_date", models.DateField(verbose_name="예약일자")),
                ("start_time", models.TimeField(verbose_name="시작시간")),
                ("end_time", models.TimeField(verbose_name="종료시간")),
                ("price", models.IntegerField(verbose_name="요금")),
                (
                    "is_coupon",
                    models.BooleanField(default=False, verbose_name="쿠폰여부"),
                ),
                (
                    "account_sms_status",
                    models.CharField(
                        choices=[
                            ("전송전", "전송전"),
                            ("전송완료", "전송완료"),
                            ("전송실패", "전송실패"),
                            ("입금확인전", "입금확인전"),
                        ],
                        default="전송전",
                        max_length=20,
                        verbose_name="계좌문자",
                    ),
                ),
                (
                    "complete_sms_status",
                    models.CharField(
                        choices=[
                            ("전송전", "전송전"),
                            ("전송완료", "전송완료"),
                            ("전송실패", "전송실패"),
                            ("입금확인전", "입금확인전"),
                        ],
                        default="입금확인전",
                        max_length=20,
                        verbose_name="완료문자",
                    ),
                ),
                (
                    "reservation_status",
                    models.CharField(
                        choices=[("신청", "신청"), ("확정", "확정"), ("취소", "취소")],
                        default="신청",
                        max_length=20,
                        verbose_name="예약상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
            ],
            options={
                "verbose_name": "예약",
                "verbose_name_plural": "예약 목록",
                "db_table": "reservations",
                "ordering": ["-reservation_date", "-start_time"],
            },
        ),
        migrations.CreateModel(
            name="CouponHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=100, verbose_name="예약자명"),
                ),
                (
                    "room_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="예약룸명"
                    ),
                ),
                ("transaction_date", models.DateField(verbose_name="거래일자")),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="시작시간"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="종료시간"),
                ),
                ("remaining_time", models.IntegerField(verbose_name="잔여시간(분)")),
                (
                    "used_or_charged_time",
                    models.IntegerField(verbose_name="사용/충전시간(분)"),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("충전", "충전"), ("사용", "사용")],
                        max_length=10,
                        verbose_name="거래유형",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="histories",
                        to="pianos.couponcustomer",
                        verbose_name="고객",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupon_histories",
                        to="pianos.reservation",
                        verbose_name="예약",
                    ),
                ),
            ],
            options={
                "verbose_name": "쿠폰 사용 이력",
                "verbose_name_plural": "쿠폰 사용 이력 목록",
                "db_table": "coupon_history",
                "ordering": ["-transaction_date", "-created_at"],
            },
        ),
    ]
