# Generated by Django 4.2.16 on 2025-12-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pianos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="naver_booking_id",
            field=models.CharField(
                default="", max_length=100, unique=True, verbose_name="예약번호"
            ),
        ),
    ]
