# Generated by Django 4.2.16 on 2025-12-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pianos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couponhistory",
            name="transaction_type",
            field=models.CharField(
                choices=[("충전", "충전"), ("사용", "사용"), ("환불", "환불")],
                max_length=10,
                verbose_name="거래유형",
            ),
        ),
    ]
