# Generated by Django 4.2.16 on 2025-12-15 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pianos", "0002_alter_couponhistory_transaction_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="couponhistory",
            options={
                "ordering": ["-created_at", "-transaction_date"],
                "verbose_name": "쿠폰 사용 이력",
                "verbose_name_plural": "쿠폰 사용 이력 목록",
            },
        ),
    ]
