# Generated by Django 4.2.16 on 2025-12-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pianos", "0002_reservation_naver_booking_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="거래고유번호"
                    ),
                ),
                ("transaction_date", models.DateField(verbose_name="거래일자")),
                ("transaction_time", models.TimeField(verbose_name="거래시간")),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("입금", "입금"), ("출금", "출금")],
                        max_length=10,
                        verbose_name="거래구분",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="거래금액")),
                ("balance", models.IntegerField(verbose_name="거래후잔액")),
                (
                    "depositor_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="입금자명"
                    ),
                ),
                ("memo", models.TextField(blank=True, verbose_name="거래메모")),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("확정전", "확정전"),
                            ("확정완료", "확정완료"),
                            ("취소", "취소"),
                        ],
                        default="확정전",
                        max_length=10,
                        verbose_name="매칭상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="수집일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "matched_reservations",
                    models.ManyToManyField(
                        blank=True,
                        related_name="matched_transactions",
                        to="pianos.reservation",
                        verbose_name="매칭된예약들",
                    ),
                ),
            ],
            options={
                "verbose_name": "계좌 거래 내역",
                "verbose_name_plural": "계좌 거래 내역 목록",
                "db_table": "account_transactions",
                "ordering": ["-transaction_date", "-transaction_time"],
                "indexes": [
                    models.Index(
                        fields=["-transaction_date", "-transaction_time"],
                        name="account_tra_transac_a7396b_idx",
                    ),
                    models.Index(
                        fields=["match_status"], name="account_tra_match_s_1bfce6_idx"
                    ),
                    models.Index(
                        fields=["depositor_name"], name="account_tra_deposit_f5212f_idx"
                    ),
                ],
            },
        ),
    ]
