# Generated by Django 4.2.16 on 2025-12-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianos', '0003_alter_messagetemplate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_proxy',
            field=models.BooleanField(default=False, verbose_name='대리예약여부'),
        ),
    ]
