# Generated by Django 4.2.16 on 2025-12-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianos', '0003_accounttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponcustomer',
            name='coupon_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couponcustomer',
            name='coupon_registered_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='couponcustomer',
            name='coupon_status',
            field=models.CharField(choices=[('활성', '활성'), ('만료', '만료')], default='활성', max_length=10),
        ),
        migrations.AddField(
            model_name='couponcustomer',
            name='coupon_type',
            field=models.IntegerField(blank=True, choices=[(10, '10시간'), (20, '20시간'), (50, '50시간'), (100, '100시간')], null=True),
        ),
        migrations.AddField(
            model_name='couponcustomer',
            name='piano_category',
            field=models.CharField(blank=True, choices=[('수입', '수입'), ('국산', '국산')], max_length=10, null=True),
        ),
    ]
