# Generated by Django 4.2.16 on 2025-12-15 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pianos", "0003_alter_couponhistory_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="couponhistory",
            options={
                "ordering": ["-id"],
                "verbose_name": "쿠폰 사용 이력",
                "verbose_name_plural": "쿠폰 사용 이력 목록",
            },
        ),
    ]
