# Generated by Django 4.2.16 on 2025-12-14 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pianos', '0004_couponcustomer_coupon_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at', '-reservation_date', '-start_time'], 'verbose_name': '예약', 'verbose_name_plural': '예약 목록'},
        ),
    ]
