# Generated by Django 4.2.16 on 2025-12-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianos', '0004_reservation_is_proxy'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, unique=True, verbose_name='룸명')),
                ('room_pw', models.CharField(blank=True, default='', max_length=50, verbose_name='비밀번호')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
