# Generated by Django 5.0 on 2025-12-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pianos", "0005_alter_couponhistory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="extra_people_qty",
            field=models.PositiveIntegerField(default=0, verbose_name="인원추가수량"),
        ),
    ]
