# Generated by Django 5.0 on 2025-12-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pianos", "0005_roompassword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couponhistory",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("충전", "충전"),
                    ("사용", "사용"),
                    ("환불", "환불"),
                    ("수동", "수동"),
                ],
                max_length=10,
                verbose_name="거래유형",
            ),
        ),
    ]
