# Generated by Django 4.2.16 on 2025-12-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianos', '0005_alter_reservation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('PAYMENT_GUIDE', '입금 안내'), ('CONFIRMATION', '확정 안내'), ('COUPON_CANCEL_TIME', '쿠폰 취소(잔여시간 부족)'), ('COUPON_CANCEL_TYPE', '쿠폰 취소(유형 불일치)'), ('NORMAL_CANCEL_CONFLICT', '일반 취소(동시간대 선입금 우선)'), ('DAWN_CONFIRM', '새벽 예약 확인')], max_length=64, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
