# Generated by Django 4.2.16 on 2025-12-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pianos", "0007_alter_messagetemplate_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationControl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "자동화 제어",
                "verbose_name_plural": "자동화 제어",
                "db_table": "automation_control",
            },
        ),
        migrations.AlterField(
            model_name="messagetemplate",
            name="code",
            field=models.CharField(
                choices=[
                    ("PAYMENT_GUIDE", "입금 안내 - 기본"),
                    ("PAYMENT_GUIDE_EXAM", "입금 안내 - 입시기간"),
                    ("PAYMENT_GUIDE_PROXY", "입금 안내 - 대리 예약"),
                    ("PAYMENT_GUIDE_ADD_PERSON", "입금 안내 - 인원 추가"),
                    (
                        "PAYMENT_GUIDE_ADD_PERSON_AND_PROXY",
                        "입금 안내 - 대리 예약 & 인원 추가",
                    ),
                    ("CONFIRMATION", "확정 안내"),
                    ("CONFIRMATION_EXAM", "확정 안내 - 입시기간"),
                    ("COUPON_CANCEL_TIME", "쿠폰 취소(잔여시간 부족)"),
                    ("COUPON_CANCEL_TYPE", "쿠폰 취소(유형 불일치)"),
                    ("NORMAL_CANCEL_CONFLICT", "일반 취소(동시간대 선입금 우선)"),
                    ("NORMAL_CANCEL_TIMEOUT", "일반 취소(입금기한 초과)"),
                    ("DAWN_CONFIRM", "새벽 예약 확인"),
                ],
                max_length=64,
                unique=True,
            ),
        ),
    ]
