# Generated by Django 4.2.16 on 2025-12-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pianos", "0008_automationcontrol_alter_messagetemplate_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="couponcustomer",
            name="phone_number",
            field=models.CharField(max_length=20, verbose_name="전화번호"),
        ),
        migrations.AddConstraint(
            model_name="couponcustomer",
            constraint=models.UniqueConstraint(
                fields=("phone_number", "piano_category"),
                name="uniq_coupon_wallet_per_phone_and_category",
            ),
        ),
    ]
