# Generated by Django 4.2.16 on 2025-12-18 06:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pianos', '0009_alter_couponcustomer_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noti_type', models.CharField(choices=[('COUPON_BALANCE_NEXTDAY', 'Coupon balance next day (AlimTalk)')], max_length=64)),
                ('target_date', models.DateField(help_text='기준일(예: 전날 이용자에게 다음날 보내면, 전날 날짜)')),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('SENT', 'SENT'), ('FAILED', 'FAILED'), ('SKIPPED', 'SKIPPED')], default='PENDING', max_length=16)),
                ('request_id', models.CharField(blank=True, default='', max_length=128)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='pianos.couponcustomer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='notificationlog',
            constraint=models.UniqueConstraint(fields=('noti_type', 'target_date', 'customer'), name='uniq_noti_once_per_day'),
        ),
    ]
