# Generated by Django 4.2.16 on 2025-12-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pianos", "0010_reservation_request_comment_notificationlog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="owner_request_noti_status",
            field=models.CharField(
                choices=[
                    ("전송전", "전송전"),
                    ("전송완료", "전송완료"),
                    ("전송실패", "전송실패"),
                ],
                default="전송전",
                max_length=20,
            ),
        ),
    ]
