# Generated by Django 4.2.16 on 2025-12-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianos', '0011_reservation_owner_request_noti_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiopolicy',
            name='exam_daily_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studiopolicy',
            name='exam_daily_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
