# Generated by Django 4.2.16 on 2025-12-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianos', '0012_studiopolicy_exam_daily_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='noti_type',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='target_date',
            field=models.DateField(),
        ),
    ]
