# Generated by Django 4.2.16 on 2026-01-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianos', '0014_alter_messagetemplate_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponhistory',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='수정 사유'),
        ),
    ]
