# Generated by Django 4.2.16 on 2026-01-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianos', '0015_couponhistory_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_change_badge',
            field=models.BooleanField(default=False, verbose_name='변경 배지 예약 여부'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_change_event_handled',
            field=models.BooleanField(default=False, verbose_name='변경 이벤트 처리 완료 여부'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('신청', '신청'), ('확정', '확정'), ('취소', '취소'), ('변경', '변경')], default='신청', max_length=20, verbose_name='예약상태'),
        ),
    ]
