# Generated by Django 4.2.16 on 2026-01-07 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianos', '0016_reservation_is_change_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttransaction',
            name='normalized_depositor_name',
            field=models.CharField(blank=True, db_index=True, max_length=120, verbose_name='입금자명(정규화)'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='normalized_customer_name',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
    ]
