# Generated by Django 4.2.16 on 2026-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pianos', '0017_accounttransaction_normalized_depositor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roompassword',
            name='room_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='룸 번호'),
        ),
    ]
